### ISSUE TITLE
4-Tracks filtering

### ISSUE THREAD

**Issue by MariaTerzieva** [HackBulgaria/Ruby-on-Rails-1#3]
I have another question about `Playlist#find_by`. :innocent:

What is the playlist that is returned supposed to contain - the tracks that are matched by all filters or the tracks that are matched by some filter from all the filters that are passed as argument?

**Comment by gsamokovarov** [comment]
The tracks matched by all the filters ;)

**Comment by MariaTerzieva** [comment]
Thank you! You can close this issue now, too.
